receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  file:
    path: ./otlp-logs.log

  logging:
    verbosity: detailed

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]


