receivers:
  otlp:
    protocols:
      grpc:

exporters:
  file:
    path: ./otlp-logs.log
    flush_interval: 1

  logging:
    verbosity: basic
  
processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]
